# VN30 Stock Price Prediction System - Main Configuration
# This file contains the main configuration for the VN30 prediction system

# Project Information
project:
  name: "VN30 Stock Price Prediction System"
  version: "1.0.0"
  description: "Research tool for predicting VN30 stock prices using quantitative finance methodologies"

# Environment Configuration
environment:
  name: "development"  # Options: development, research, production
  log_level: "INFO"    # Options: DEBUG, INFO, WARNING, ERROR
  random_seed: 42

# Data Configuration
data:
  # Data sources configuration
  sources:
    primary: "vnstock"    # Primary data source
    fallbacks: ["TCBS", "VCI", "MSN", "FMARKET"]

  # Data storage paths
  paths:
    raw: "data/raw"
    processed: "data/processed"
    qlib_format: "data/qlib_format"

  # Historical data requirements
  history:
    min_years: 5
    max_years: 10

  # Data validation settings
  validation:
    missing_value_threshold: 0.1  # 10% missing values allowed
    outlier_std_threshold: 3.0    # 3 standard deviations for outliers

# Feature Engineering Configuration
features:
  # Technical indicators to generate
  technical_indicators:
    - "SMA"      # Simple Moving Average
    - "EMA"      # Exponential Moving Average
    - "RSI"      # Relative Strength Index
    - "MACD"     # Moving Average Convergence Divergence
    - "BBANDS"   # Bollinger Bands
    - "STOCH"    # Stochastic Oscillator

  # Fundamental features
  fundamental_features:
    - "P/E"      # Price to Earnings
    - "P/B"      # Price to Book
    - "ROE"      # Return on Equity
    - "ROA"      # Return on Assets
    - "DEBT_RATIO"  # Debt to Equity Ratio

  # Feature scaling options
  scaling:
    method: "standard"  # Options: standard, minmax, robust
    clip_outliers: true

# Model Configuration
models:
  # Baseline models
  baseline:
    - "LightGBM"
    - "XGBoost"
    - "MLP"
    - "LSTM"

  # Advanced models
  advanced:
    - "TFT"      # Temporal Fusion Transformer
    - "GRU"      # Gated Recurrent Unit
    - "TCN"      # Temporal Convolutional Network
    - "TRA"      # Transformer
    - "ADARNN"   # Attention-based Deep Adaptive RNN

  # Ensemble methods
  ensemble:
    - "Reinforcement Learning"
    - "DDG-DA"
    - "DoubleEnsemble"
    - "Meta-Learning"

  # Training configuration
  training:
    batch_size: 64
    epochs: 100
    validation_split: 0.2
    early_stopping_patience: 10

  # Cross-validation
  cross_validation:
    method: "purged_kfold"
    n_splits: 5
    purge_window: 20

# Prediction Configuration
prediction:
  # Forecast horizons (in trading days)
  horizons:
    short_term: 20   # 1 month
    medium_term: 60  # 3 months
    long_term: 120   # 6 months

  # Confidence intervals
  confidence_level: 0.95

  # Prediction output
  output:
    include_confidence_intervals: true
    include_feature_importance: true
    save_predictions: true

# Evaluation Configuration
evaluation:
  # Performance metrics
  metrics:
    - "IC"              # Information Coefficient
    - "Rank_IC"         # Rank Information Coefficient
    - "MSE"             # Mean Squared Error
    - "MAE"             # Mean Absolute Error
    - "Sharpe_Ratio"    # Sharpe Ratio
    - "Max_Drawdown"    # Maximum Drawdown

  # Benchmark comparison
  benchmarks:
    - "VN30_Index"      # VN30 Index
    - "Buy_and_Hold"    # Buy and Hold Strategy

  # Backtesting configuration
  backtesting:
    transaction_cost: 0.0015  # 0.15% transaction cost
    position_limit: 0.1       # 10% max position per stock
    rebalance_frequency: "monthly"

# Logging Configuration
logging:
  # Log file settings
  file:
    path: "logs/vn30_prediction.log"
    max_size: "10MB"
    backup_count: 5

  # Console logging
  console:
    enabled: true
    format: "detailed"

  # Log levels for different modules
  levels:
    data: "INFO"
    model: "INFO"
    evaluation: "INFO"
    system: "WARNING"

# API Configuration
api:
  # External API settings
  vnstock:
    timeout: 30
    max_retries: 3
    backoff_factor: 2

  # Rate limiting
  rate_limit:
    requests_per_minute: 60
    burst_limit: 10

# System Configuration
system:
  # Performance settings
  performance:
    max_memory_usage: "8GB"
    parallel_workers: 4
    use_gpu: false  # Set to true if GPU available

  # File handling
  file_handling:
    chunk_size: 10000
    compression: "gzip"

  # Error handling
  error_handling:
    max_retries: 3
    retry_backoff: 2
    graceful_degradation: true
